### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bhralz** [ZhihuaLiuEd/canetbrats#1]
Hi,
Thanks for your great effort,
but step by step tracking your guidlines arised an error in training  (train.py) step as below:

TypeError: __init__() got an unexpected keyword argument 'norm_layer'

How this can be solved?
please reply as soon.
Thanks again

**Comment by ZhihuaLiuEd** [comment]
Hi, can you give me your error line number? or the full error information?

**Comment by bhralz** [comment]
\experiments\canet.py", line 83, in __init__
    super(CANetOutput, self).__init__(nclass, backbone, norm_layer=norm_layer, **kwargs)

TypeError: __init__() got an unexpected keyword argument 'norm_layer'

**Comment by ZhihuaLiuEd** [comment]
Hi, try again on the updated code.

I will test the code again in the next few days.
